name: RepairChest
main: de.mahagst.risingworld.repairchest.RepairChestPlugin
version: 1.2.0
author: mahagst
description: Repair chests to restore durability of items
website: https://github.com/HaggerShose/rw-repair-chest/releases/latest
